import React from "react";
import { Poppins, Permanent_Marker } from "next/font/google";
import { ToastContainer, Bounce } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from "../components/Base/Header.jsx";
import "../i18n.js";
import "./globals.css";
import LanguageContext from "@/contexts/LanguageContext.jsx";
import Footer from "@/components/Base/Footer.jsx";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const permanentMarker = Permanent_Marker({
  variable: "--font-permanent-marker",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${permanentMarker.variable} antialiased`}
      >
        <React.Suspense fallback="loading...">
          <LanguageContext>
            <Header />
            <ToastContainer
              position="top-center"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="dark"
              transition={Bounce}
            />
            {children}
            <Footer />
          </LanguageContext>
        </React.Suspense>
      </body>
    </html>
  );
}
